service: static-file-handler-test-basic

plugins:
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes

custom:
  apiGateway:
    binaryMediaTypes:
      # You can use the wildcard character (*) to cover multiple media types per https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html
      # NOTE: Using */* has a side effect as noted at https://github.com/activescott/serverless-aws-static-file-handler
      # IANA descrete type wildcards from: https://www.iana.org/assignments/media-types/media-types.xhtml
      - application/*
      - audio/*
      - font/*
      - image/*
      - video/*

provider:
  name: aws
  runtime: nodejs14.x

functions:
  html:
    handler: handler.html
    events:
      - http:
          path: /
          method: get
  png:
    handler: handler.png
    events:
      - http:
          path: png
          method: get
