language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
env:
  global:
    # GH_TOKEN (Github for semantic-release)
    - secure: "YsRmVVbwopeWG8yUECvGVmjDcWpXIhmaNVIMgbCCvX4a5VkxpbQ51f77g1tP5Miotkp/A4MxWZ+M0mCSDPzvLEFg+cJMkWVOeypZ4+aTTc+/tYdntl8iVk0sPVC9si4BcP3RxNMoyRvTYezLWrymVYTgztNLDzNPPbSDn7BZsiCe2XCTCk6t1er5BIiCtczAZ7gZ73nuA0RwIFo2H+bUD8pSqfbGkg3B/JUv1B2S+cLJjN2+5mhbC6maV0JZeUaUxqbvAAw+UFXjFeBIeGbDdjplOQN4vSBq2h0irFUAQOwlDBr1vKUjTrtaZn/pb0Z/ObMCa7IrQq9s3NP4po9WPajN3TAlKlYf9iIcJu0mXPLawylyCKVJIq/4J3Pga3rIMTIiVEjtDOsrZLD/6LLsoEEANW+AgZYJdq5aWqme9nfd5bjq/0NWxz7EjERqkFVKyrp3OsanyRmCKMEj3wz938D6fHwc2HtN8UdBjV1i+QzpWj+YJ5r0vw5hw0GMTNPU/FOqjXgCQ47O+7Q8/n1z+gEfLjtwgnwfLGf85ipoNp/FgvpbitwcYt9HhDhRaus/NE0rQOHxH7xcqknWNU53liE5EIDt9gKlAwJd+J7sItPIAsrXF5ZHIawp12xL+bNBbErzXUKJcoEtyOzrofwGeU29eibDNj6VIiXovs+PTZ0="
    # NPM_TOKEN
    - secure: "RfgH5t11XHiLhU7oh4jjtm6gnWAFXl68S4iTzWT1FKkMBz7dUKd6VHyIsEK3IBvGOnBt1/50xhHBm9impsgZ1vp7xFJWFBk6sPwYoHgKuE03pqO06bYMY2PMTAWYzVl/4g2Gy3DO65RyHu5H/JVuePB3JjaIf8Tj1wf+1mDa7JiaCaxbdLs+y6/Xsuu/GN504i/pQba8eVv6sj6naV+HhQGkqtV3Sgtza0WI23eKMXP6I6dG5mO8AKDKeP5VZqFoIhppXX8ckgSx9oMXWmZlvRZAmlwmnCNEwJxxsqzMWMXhQuVzKaZDlINfVHZERCliyPMOybSx88hYzaNls1ZG6fcCIzX9a26AskirsbzpWNZFfTmxvuYvVGh04aBc77xwXEm8Jq31rfp3Hj3/tBTOWyp5/oXvanL45Vd0fXacK9l50y/97juPILckOyFz0bg51fdyF33PxepJ7cxQ4L+ASDeM7SLnfVekiobzevBAAK3UqsB0gDnwwi53alGQtIRmqAvoz3aP0jyfiIrpz337cuV3SbsF88b0bSACq9TdCaoOKhPbSuWQFS0agTeCbxpSYMex87IljKKfO2DY4nL/ByPVTkYmIJtt/RhewtQbT3RbVDdpB6ESWrglu5D2UX3IM90q1m/pn96U2Xm8SD5IFfHGVQWR8lii/PJuEUGyFRg="
cache:
  npm: false # because we're using `npm ci` as install script (but not auto-detected because package-lock.json not in root); https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support
  directories:
    - $HOME/.npm # https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support

# NOTE: this is basically the first "stage" with the name "Test"
before_install: cd ./src
install: npm ci # https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#npm-ci-support

script:
  - echo "Running tests against $(node -v) ..."
  - npm run lint
  - npm run test

after_success:
  - test "$TRAVIS_NODE_VERSION" = "lts/*" && npm run coverage-publish

jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: semantic-release
      node_js: lts/*
      # build it so the necessary distributable files exist
      script: npm build
      deploy:
        - provider: script
          skip_cleanup: true
          script:
            - ./node_modules/.bin/semantic-release --debug
          on:
            # Override `deploy` default of master; semantic-release will decide which branches to deploy on!
            all_branches: true
