service: static-file-handler-demo-proxy

plugins:
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes

custom:
  # TODO: Replace with built-in plugin
  apigwBinary:
    types:
      - "*/*" # Using */* doesn't have side effects that I can tell. The HTML response works fine.

provider:
  name: aws
  runtime: nodejs8.10

functions:
  binary:
    handler: handler.binary
    events:
      - http:
          path: /binary/{pathvar+}
          method: get
  png:
    handler: handler.png
    events:
      - http:
          path: png
          method: get
  jpg:
    handler: handler.jpg
    events:
      - http:
          path: jpg
          method: get
  html:
    handler: handler.html
    events:
      - http:
          path: /
          method: get
