service: static-file-handler-demo-offline

plugins:
  - serverless-offline
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes

custom:
  apiGateway:
    binaryMediaTypes:
      - image/png
      - image/jpeg
      - "*/*" # Using */* doesn't have side effects that I can tell. The HTML response works fine.

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  html:
    handler: handler.root
    events:
      - http:
          path: /
          method: get

  binary:
    handler: handler.binary
    events:
      - http:
          path: /binary/{pathvar+}
          method: get
