service: static-file-handler-demo-offline

plugins:
  - serverless-offline
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes

custom:
  apiGateway:
    binaryMediaTypes:
      # You can use the wildcard character (*) to cover multiple media types per https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-payload-encodings.html
      # NOTE: Using */* has a side effect as noted at https://github.com/activescott/serverless-aws-static-file-handler
      # IANA descrete type wildcards from: https://www.iana.org/assignments/media-types/media-types.xhtml
      - application/*
      - audio/*
      - font/*
      - image/*
      - video/*

provider:
  name: aws
  runtime: nodejs20.x
  lambdaHashingVersion: 20201221

functions:
  html:
    handler: handler.root
    events:
      - http:
          path: /
          method: get

  binary:
    handler: handler.binary
    events:
      - http:
          path: /binary/{pathvar+}
          method: get
