on:
  pull_request:
    branches:
      - main
      - beta
      - alpha
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set ref value
        id: set_ref
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        # The intent here is to checkout the PR's branch/commit head when it is an open PR
        # ...but checkout the target branch's head commit when it is a PR being merged or a commit directly to the branch.
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]] && [[ "${{ github.event.pull_request.merged }}" == "false" ]]; then
            echo "REF=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          else
            echo "REF=" >> $GITHUB_ENV
          fi

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.REF }}

      - name: Print commit info and workflow file content
        run: |
          echo "Commit SHA: $(git rev-parse HEAD)"
          echo "Commit Message: $(git log --format=%B -n 1 HEAD)"
          echo "Contents of the debug-workflow file:"
          cat .github/workflows/debug-workflow.yml
