# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#deployment
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
on: [deployment, workflow_dispatch]

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        # 7cef3de3dcfa68b55e3952f8dd836ca10e51af64 is from Nov 15, 2022
        # https://github.com/ambilykk/deployment-auto-approve
        uses: ambilykk/deployment-auto-approve@7cef3de3dcfa68b55e3952f8dd836ca10e51af64
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          environment: aws
